name: Trigger Action to run check update data python script

on:
  schedule:
    - cron: 45 23 4,20 * * # every 10th and 20th of each month

jobs:
  run-python-check-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install a specific version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ">=0.4.0"

      - name: Install dependencies
        run: uv sync 

      - name: run python check update
        run: uv run pipelines/tasks/check_data_update

